jdbc:
  url: "jdbc:postgresql://127.0.0.1:5000/test"
  user: "test"
  password: "test"

spring:
  datasource:
    username: "test"
    password: "test"
    url:      "jdbc:postgresql://127.0.0.1:5000/test"
    driverClassName: "org.postgresql.Driver"
  jpa:
    showSql: "false"
#    driver-class: "org.postgresql.Driver"